Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/d/Library/Python/3.11/lib/python/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import networkx as nx
import matplotlib.pyplot as plt

G = nx.DiGraph()
G.add_node("Data", pos=(-2500, 700))
G.add_node("Code", pos=(-4200, 0))
G.add_node("Inferences", pos=(-1000, 0))
G.add_node("Parameters", pos=(-2500, -700))
G.add_node("Updates", pos=(1500, 0))
G.add_node("Transparency", pos=(4000, 0))

G.add_edges_from([("Sensory", "Frailty")])
G.add_edges_from([("Cognitive", "Frailty")])
G.add_edges_from([("Muscle", "Frailty")])
G.add_edges_from([("Frailty", "ADL")])
G.add_edges_from([("ADL", "Outcome")])

pos = nx.get_node_attributes(G, 'pos')
labels = {"Inferences": "Frailty\n(Phenotype)",
          "Data": "Sensory\n(Acuity)",
          "Code": "Cognitive\n(Tasks)",
          "Parameters": "Muscle\n(Strength)",
          "Updates": "ADL\n(Independence)",
          "Transparency": "Outcome\n(Hard Endpoints)"}  # Added label for "NDI" node in the labels dictionary

# Update color for the "Scenarios" node
node_colors = ["lightblue","lightblue", "lavender", "lightblue", "lightblue", "lightblue"]
# node_colors = ["lightblue","lavender", "lavender", "lightgreen", "lightpink", "lightpink"]
# Suppress the deprecation warning
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

plt.figure(figsize=(10, 8))
nx.draw(G, pos, with_labels=False, node_size=20000, node_color=node_colors, linewidths=2, edge_color='black', style='solid')
nx.draw_networkx_labels(G, pos, labels, font_size=14) # , font_weight='bold'
nx.draw_networkx_edges(G, pos, edge_color='black', style='solid', width=2)
plt.xlim(-5000, 5000)
plt.ylim(-1000, 1000)
plt.axis("off")
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/networkx/drawing/nx_pylab.py:425[0m, in [0;36mdraw_networkx_nodes[0;34m(G, pos, nodelist, node_size, node_color, node_shape, alpha, cmap, vmin, vmax, ax, linewidths, edgecolors, label, margins)[0m
[1;32m    424[0m [38;5;28;01mtry[39;00m:
[0;32m--> 425[0m     xy [38;5;241m=[39m np[38;5;241m.[39masarray([43m[[49m[43mpos[49m[43m[[49m[43mv[49m[43m][49m[43m [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mv[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[43mnodelist[49m[43m][49m)
[1;32m    426[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/networkx/drawing/nx_pylab.py:425[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m    424[0m [38;5;28;01mtry[39;00m:
[0;32m--> 425[0m     xy [38;5;241m=[39m np[38;5;241m.[39masarray([[43mpos[49m[43m[[49m[43mv[49m[43m][49m [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m nodelist])
[1;32m    426[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

[0;31mKeyError[0m: 'Sensory'

The above exception was the direct cause of the following exception:

[0;31mNetworkXError[0m                             Traceback (most recent call last)
Cell [0;32mIn[1], line 34[0m
[1;32m     31[0m warnings[38;5;241m.[39mfilterwarnings([38;5;124m"[39m[38;5;124mignore[39m[38;5;124m"[39m, category[38;5;241m=[39m[38;5;167;01mDeprecationWarning[39;00m)
[1;32m     33[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m10[39m, [38;5;241m8[39m))
[0;32m---> 34[0m [43mnx[49m[38;5;241;43m.[39;49m[43mdraw[49m[43m([49m[43mG[49m[43m,[49m[43m [49m[43mpos[49m[43m,[49m[43m [49m[43mwith_labels[49m[38;5;241;43m=[39;49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m[43m [49m[43mnode_size[49m[38;5;241;43m=[39;49m[38;5;241;43m20000[39;49m[43m,[49m[43m [49m[43mnode_color[49m[38;5;241;43m=[39;49m[43mnode_colors[49m[43m,[49m[43m [49m[43mlinewidths[49m[38;5;241;43m=[39;49m[38;5;241;43m2[39;49m[43m,[49m[43m [49m[43medge_color[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mblack[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mstyle[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43msolid[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m     35[0m nx[38;5;241m.[39mdraw_networkx_labels(G, pos, labels, font_size[38;5;241m=[39m[38;5;241m14[39m) [38;5;66;03m# , font_weight='bold'[39;00m
[1;32m     36[0m nx[38;5;241m.[39mdraw_networkx_edges(G, pos, edge_color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mblack[39m[38;5;124m'[39m, style[38;5;241m=[39m[38;5;124m'[39m[38;5;124msolid[39m[38;5;124m'[39m, width[38;5;241m=[39m[38;5;241m2[39m)

File [0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/networkx/drawing/nx_pylab.py:121[0m, in [0;36mdraw[0;34m(G, pos, ax, **kwds)[0m
[1;32m    118[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mwith_labels[39m[38;5;124m"[39m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m kwds:
[1;32m    119[0m     kwds[[38;5;124m"[39m[38;5;124mwith_labels[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;124m"[39m[38;5;124mlabels[39m[38;5;124m"[39m [38;5;129;01min[39;00m kwds
[0;32m--> 121[0m [43mdraw_networkx[49m[43m([49m[43mG[49m[43m,[49m[43m [49m[43mpos[49m[38;5;241;43m=[39;49m[43mpos[49m[43m,[49m[43m [49m[43max[49m[38;5;241;43m=[39;49m[43max[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwds[49m[43m)[49m
[1;32m    122[0m ax[38;5;241m.[39mset_axis_off()
[1;32m    123[0m plt[38;5;241m.[39mdraw_if_interactive()

File [0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/networkx/drawing/nx_pylab.py:303[0m, in [0;36mdraw_networkx[0;34m(G, pos, arrows, with_labels, **kwds)[0m
[1;32m    300[0m [38;5;28;01mif[39;00m pos [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    301[0m     pos [38;5;241m=[39m nx[38;5;241m.[39mdrawing[38;5;241m.[39mspring_layout(G)  [38;5;66;03m# default to spring layout[39;00m
[0;32m--> 303[0m [43mdraw_networkx_nodes[49m[43m([49m[43mG[49m[43m,[49m[43m [49m[43mpos[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mnode_kwds[49m[43m)[49m
[1;32m    304[0m draw_networkx_edges(G, pos, arrows[38;5;241m=[39marrows, [38;5;241m*[39m[38;5;241m*[39medge_kwds)
[1;32m    305[0m [38;5;28;01mif[39;00m with_labels:

File [0;32m/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/networkx/drawing/nx_pylab.py:427[0m, in [0;36mdraw_networkx_nodes[0;34m(G, pos, nodelist, node_size, node_color, node_shape, alpha, cmap, vmin, vmax, ax, linewidths, edgecolors, label, margins)[0m
[1;32m    425[0m     xy [38;5;241m=[39m np[38;5;241m.[39masarray([pos[v] [38;5;28;01mfor[39;00m v [38;5;129;01min[39;00m nodelist])
[1;32m    426[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[0;32m--> 427[0m     [38;5;28;01mraise[39;00m nx[38;5;241m.[39mNetworkXError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNode [39m[38;5;132;01m{[39;00merr[38;5;132;01m}[39;00m[38;5;124m has no position.[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    429[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(alpha, Iterable):
[1;32m    430[0m     node_color [38;5;241m=[39m apply_alpha(node_color, alpha, nodelist, cmap, vmin, vmax)

[0;31mNetworkXError[0m: Node 'Sensory' has no position.

